language: go

go:
  - 1.x

before_install:
  - go get -v golang.org/x/lint/golint

install:
  - go install -race -v std
  - go get -race -t -v ./...
  - go install -race -v ./...

script:
  - $HOME/gopath/bin/golint .
  - go test -cpu=2 -race -v ./...
  - go test -cpu=2 -covermode=atomic ./...
